build: false

environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - SET PATH=%PYTHON%;%path%
  - mklink /D C:\Python34\python3.exe C:\Python34\python.exe
  - SET PATH=%PATH%;C:\Python34\python3.exe

build_script:
  - "python3 --version"
  - "python --version"
  - "pushd test"
  - "python test.py"
  - "popd"
