build: false

environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - SET PATH=%PYTHON%;%path%

build_script:
  - ps: set python3 "C:\Python34"
  - "python --version"
  - "pushd test"
  - "python test.py"
  - "popd"
