#!/usr/bin/env python3
# -*- coding: utf-8 -*-

""" Git post-commit hook to remove private values """

import sys, subprocess

from cmnds import run_cmnds


def main():

	cmnds = ['python3 ../py-hook.py "post" "source.dir" "../backup.dir"',
	 'python3 ../py-hook.py "post" "other.source.dir" "../other.backup.dir"']
	
	run_cmnds(cmnds)
	

if __name__ == "__main__":
	main()
